from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CalibrationCase:
    name: str
    description: str
    directives_include: tuple[str, ...] = ()
    directives_exclude: tuple[str, ...] = ()
    ce_include: tuple[str, ...] = ()
    ce_exclude: tuple[str, ...] = ()
    standards_include: tuple[str, ...] = ()
    standards_exclude: tuple[str, ...] = ()
    review_include: tuple[str, ...] = ()
    review_exclude: tuple[str, ...] = ()
    missing_include: tuple[str, ...] = ()
    missing_exclude: tuple[str, ...] = ()
    expected_scope_route: str | None = None
    expected_primary_route_family: str | None = None
    expected_primary_route_standard: str | None = None
    expected_product_type: str | None = None
    expected_product_match_stage: str | None = None
    expected_route_confidence: str | None = None
    assert_primary_route: bool = False
    assert_product_type: bool = False


CALIBRATION_CASES: tuple[CalibrationCase, ...] = (
    CalibrationCase(
        name="non_radio_mains_appliance",
        description="230 V electric kettle, household use, no wireless connectivity",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        ce_include=("LVD", "EMC"),
        ce_exclude=("RED",),
        standards_include=("EN 60335-2-15", "EN 60335-1", "EN 55014-1"),
        standards_exclude=("EN 62368-1",),
        missing_exclude=("cloud_dependency", "software_update_route", "smart_access_model"),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-15",
        expected_product_type="electric_kettle",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smart_home_appliance_wifi_app",
        description="Smart washing machine with Wi-Fi, Bluetooth, cloud account, OTA firmware updates, 230 V mains",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        ce_include=("RED", "RED_CYBER"),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 60335-2-7", "EN 60335-1", "EN 301 489-1", "EN 300 328"),
        standards_exclude=("EN 62368-1",),
        review_include=("EN 18031-2",),
        missing_include=("radio_rf_detail", "data_storage_scope"),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-7",
        expected_product_type="washing_machine",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="battery_non_radio_device",
        description="Rechargeable handheld barcode scanner, battery powered, USB-C charging, no wireless connectivity",
        directives_include=("EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        ce_include=("LVD", "EMC"),
        ce_exclude=("RED",),
        standards_include=("EN 62368-1", "EN 55032", "EN 55035", "EN 62133-2"),
        missing_include=("battery_chemistry",),
        missing_exclude=("cloud_dependency", "software_update_route"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="industrial_handheld_scanner",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="bluetooth_only_accessory",
        description="Bluetooth-only accessory remote shutter button, coin-cell battery, no app account, no cloud",
        directives_include=("RED",),
        directives_exclude=("RED_CYBER", "LVD", "EMC"),
        ce_include=("RED",),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 300 328", "EN 301 489-1"),
        standards_exclude=("EN 62368-1",),
        missing_include=("radio_rf_detail", "battery_chemistry"),
        missing_exclude=("cloud_dependency", "smart_access_model"),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="radio_cloud_ota_product",
        description="Wi-Fi 6 mesh router with cloud account and OTA updates",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        ce_include=("RED", "RED_CYBER"),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 55032", "EN 301 893"),
        review_include=("EN 18031-2", "CRA review"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="mesh_wifi_system",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wearable_sensor",
        description="Wearable heart-rate sensor chest strap with Bluetooth, skin contact, rechargeable battery",
        directives_include=("RED", "BATTERY", "GDPR"),
        directives_exclude=("LVD", "EMC", "RED_CYBER"),
        ce_include=("RED",),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 62209-1528", "EN 50566"),
        review_include=("Biocompatibility / skin-contact review",),
        missing_include=("radio_rf_detail", "data_storage_scope", "body_contact_materials"),
        missing_exclude=("cloud_dependency", "smart_access_model"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict_wearable",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="heart_rate_monitor",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="household_60335_logic",
        description="Hair dryer, 230 V mains, consumer household use",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED",),
        standards_include=("EN 60335-2-23", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-23",
        assert_primary_route=True,
    ),
    CalibrationCase(
        name="optical_led_product",
        description="Smart LED desk lamp with Wi-Fi app control, mains powered",
        directives_include=("RED", "RED_CYBER"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN IEC 62560", "EN 301 489-1"),
        review_include=("EN 62031",),
        expected_scope_route="appliance",
        expected_primary_route_family="lighting_device",
        expected_primary_route_standard="EN IEC 62560",
        expected_product_type="smart_desk_lamp",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="laser_product",
        description="Laser home projector, Wi-Fi, Bluetooth, mains powered, class 1 laser source",
        directives_include=("RED", "RED_CYBER"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 60825-1", "EN 62471"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="home_projector",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="battery_handheld_tool",
        description="Cordless power drill, 18 V lithium-ion battery, consumer handheld tool",
        directives_include=("MD", "MACH_REG", "BATTERY"),
        directives_exclude=("RED", "LVD"),
        ce_include=("MD",),
        standards_include=("EN 62841-2-1", "EN 62841-1"),
        expected_scope_route="machinery",
        expected_primary_route_family="machinery_power_tool",
        expected_primary_route_standard="EN 62841-2-1",
        expected_product_type="cordless_power_drill",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="machine_like_powered_tool",
        description="Corded circular saw, 230 V, 1800 W, for professional wood cutting",
        directives_include=("MD", "MACH_REG"),
        directives_exclude=("RED",),
        review_include=("Power tool safety review",),
        expected_scope_route="machinery",
        expected_primary_route_family="machinery_power_tool",
        expected_primary_route_standard="Power tool safety review",
        expected_product_type="portable_power_saw",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ev_charging_station",
        description="Smart EV charging station wallbox, mode 3, AC charging, Type 2 connector, Wi-Fi, app control",
        directives_include=("RED", "RED_CYBER", "CRA"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN IEC 61851-1", "EN IEC 61851-21-2"),
        review_include=("EN 62196-2",),
        expected_scope_route="appliance",
        expected_primary_route_family="ev_charging",
        expected_primary_route_standard="EN IEC 61851-1",
        expected_product_type="ev_charger_home",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ev_connector_cable",
        description="EV charging connector cable, Type 2 vehicle connector, tethered cable accessory only, no electronics",
        directives_include=("LVD",),
        directives_exclude=("RED",),
        review_include=("EN 62196-2",),
        standards_exclude=("EN IEC 61851-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="ev_connector_accessory",
        expected_primary_route_standard="EN 62196-2",
        expected_product_type="ev_connector_accessory",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="simple_accessory",
        description="Passive USB-C to HDMI adapter cable, no radio, no battery",
        directives_exclude=("RED", "LVD"),
        standards_exclude=("EN 62368-1", "EN 60335-1"),
        missing_include=("external_psu",),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ambiguous_partial_facts",
        description="smart device for home use with app",
        directives_exclude=("RED", "LVD"),
        standards_exclude=("EN 62368-1", "EN 60335-1"),
        missing_include=("power_source", "cloud_dependency"),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="non_radio_iron_household",
        description="dry electric iron, 230 V mains, household use",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 60335-2-3", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-3",
        expected_product_type="electric_iron",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="portable_air_conditioner_non_radio",
        description="portable air conditioner, mains powered, household use, no wireless connectivity",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 60335-2-40", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-40",
        expected_product_type="portable_air_conditioner",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="steam_cleaner_non_radio",
        description="steam cleaner for floors, mains powered",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 60335-2-79", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-79",
        expected_product_type="steam_cleaner",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smoke_co_alarm_battery",
        description="smoke alarm with carbon monoxide detection, battery powered",
        directives_include=("EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("EN 14604", "EN 50291-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="life_safety_alarm",
        expected_primary_route_standard="EN 14604",
        expected_product_type="smoke_co_alarm",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smart_plug_local_only",
        description="smart plug with local only control and no cloud",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("EN 62368-1",),
        standards_exclude=("EN 300 328",),
        missing_exclude=("radio_rf_detail", "cloud_dependency"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="smart_plug",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wifi_extender_dual_band",
        description="wifi range extender with dual-band support",
        directives_include=("RED", "RED_CYBER", "CRA"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 300 328"),
        review_include=("CRA review", "EN 303 645 review"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="wifi_extender",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="office_printer_wifi",
        description="home office inkjet printer with wifi",
        directives_include=("RED", "RED_CYBER", "CRA"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 300 328"),
        review_include=("CRA review",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="office_printer",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="document_scanner_usb",
        description="A4 document scanner with USB",
        directives_include=("LVD", "EMC", "CRA"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032"),
        standards_exclude=("EN 300 328",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="document_scanner",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="nvr_recorder_poe",
        description="network video recorder with PoE ports and 2TB storage",
        directives_include=("LVD", "EMC", "CRA", "GDPR"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032"),
        review_include=("CRA review", "GDPR review"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="nvr_dvr_recorder",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="power_bank_usb_c",
        description="power bank with usb-c charging",
        directives_include=("EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62133-2",),
        review_include=("EN 62368-1", "UN 38.3 review"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="power_bank",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="usb_wall_charger_pd",
        description="65W usb-c wall charger with power delivery",
        directives_include=("LVD", "EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032"),
        review_include=("Charger / external PSU review",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="usb_wall_charger",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wireless_charger_pad",
        description="wireless charger charging pad",
        directives_include=("LVD", "EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("EN 62368-1", "Charger / external PSU review"),
        standards_include=("EN 62133-2",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="wireless_charger",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="external_psu_adapter",
        description="24V external power supply adapter for monitor",
        directives_include=("LVD", "EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032"),
        review_include=("Charger / external PSU review",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="external_power_supply",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wifi_security_camera",
        description="wifi security camera with cloud app and night vision",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 300 328"),
        review_include=("CRA review", "GDPR review"),
        expected_scope_route="av_ict",
        expected_product_type="smart_security_camera",
        assert_product_type=True,
    ),
    CalibrationCase(
        name="video_doorbell_connected",
        description="video doorbell with wifi and camera",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 300 328"),
        review_include=("CRA review", "GDPR review"),
        expected_scope_route="av_ict",
        expected_product_type="smart_doorbell",
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smart_lock_connected",
        description="smart lock with wifi bluetooth keypad and app control",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 14846", "EN 300 328"),
        review_include=("CRA review", "GDPR review"),
        expected_scope_route="appliance",
        expected_primary_route_family="building_hardware",
        expected_primary_route_standard="EN 14846",
        expected_product_type="smart_lock",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smart_scale_bluetooth",
        description="smart scale with bluetooth body composition tracking",
        directives_include=("RED", "BATTERY", "GDPR", "MDR"),
        directives_exclude=("LVD", "EMC"),
        review_include=("MDR borderline review",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="smart_scale",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="grow_light_indoor_garden",
        description="smart indoor garden with grow light and app control",
        directives_include=("LVD", "EMC", "CRA"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("EN IEC 62560", "EN 62471"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="smart_indoor_garden",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wired_only_monitor",
        description="monitor with wired only ethernet dock and no radio",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032"),
        standards_exclude=("EN 300 328",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="monitor",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="dishwasher_non_radio_wave3",
        description="dishwasher with no wireless connectivity",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 60335-2-5", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-5",
        expected_product_type="dishwasher",
        expected_product_match_stage="subtype",
        expected_route_confidence="medium",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="induction_hob_wave3",
        description="induction hob with touch controls",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 60335-2-6", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-6",
        expected_product_type="hob",
        expected_product_match_stage="subtype",
        expected_route_confidence="medium",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="multicooker_wave3",
        description="multicooker with pressure mode and slow cook mode",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("Household cooking appliance part-2 review",),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-1",
        expected_product_type="multicooker",
        expected_product_match_stage="subtype",
        expected_route_confidence="high",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="water_dispenser_boundary_wave3",
        description="water dispenser with chilled water",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("Water dispenser / cooler review",),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-1",
        expected_product_type="water_dispenser",
        expected_product_match_stage="family",
        expected_route_confidence="medium",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="uv_nail_lamp_boundary_wave3",
        description="uv nail lamp for gel polish",
        directives_include=("EMC",),
        directives_exclude=("RED", "RED_CYBER", "LVD"),
        review_include=("UV / irradiation application review", "Biocompatibility / skin-contact review", "EN 62471"),
        standards_exclude=("EN 62368-1",),
        missing_include=("uv_irradiation_intent", "body_treatment_scope"),
        expected_scope_route="appliance",
        expected_primary_route_family="lighting_device",
        expected_product_type="uv_nail_lamp",
        expected_product_match_stage="family",
        expected_route_confidence="low",
        assert_product_type=True,
    ),
    CalibrationCase(
        name="access_reader_wave3",
        description="badge reader for door access control",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 55032", "EN 55035"),
        review_include=("EN 62368-1",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="access_reader",
        expected_product_match_stage="subtype",
        expected_route_confidence="high",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="conference_speakerphone_wave3",
        description="conference speakerphone for meeting room",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("EN 62368-1",),
        missing_include=("power_source",),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="conference_speakerphone",
        expected_product_match_stage="subtype",
        expected_route_confidence="high",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ups_boundary_wave3",
        description="ups battery backup unit for office server",
        directives_include=("LVD", "EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        standards_include=("EN 62368-1", "EN 55032", "EN 55035"),
        review_include=("Energy storage / inverter system review", "Charger / external PSU review", "UN 38.3 review"),
        missing_include=("battery_chemistry", "energy_system_scope"),
        expected_scope_route="generic",
        expected_primary_route_family="power_system_boundary",
        expected_primary_route_standard=None,
        expected_product_type="ups",
        expected_product_match_stage="family",
        expected_route_confidence="low",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="solar_charge_controller_boundary_wave3",
        description="solar charge controller for off-grid battery bank",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        review_include=("Charger / external PSU review",),
        standards_exclude=("EN 300 328",),
        missing_include=("energy_system_scope", "installation_boundary"),
        expected_scope_route="generic",
        expected_primary_route_family="power_system_boundary",
        expected_primary_route_standard=None,
        expected_product_type="solar_charge_controller",
        expected_product_match_stage="family",
        expected_route_confidence="low",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="bottle_sterilizer_wave3",
        description="bottle sterilizer for baby feeding accessories",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER", "TOY"),
        review_include=("Sterilization / hygiene appliance review",),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-1",
        expected_product_type="bottle_sterilizer",
        expected_product_match_stage="subtype",
        expected_route_confidence="medium",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ring_light_wave3",
        description="ring light for streaming desk setup",
        directives_include=("EMC",),
        directives_exclude=("RED", "RED_CYBER", "BATTERY"),
        review_include=("EN 62471",),
        missing_include=("lighting_form_factor", "primary_function_boundary"),
        expected_scope_route="appliance",
        expected_primary_route_family="lighting_device",
        expected_product_type="ring_light",
        expected_product_match_stage="subtype",
        expected_route_confidence="medium",
        assert_product_type=True,
    ),
)


__all__ = ["CALIBRATION_CASES", "CalibrationCase"]
