from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CalibrationCase:
    name: str
    description: str
    directives_include: tuple[str, ...] = ()
    directives_exclude: tuple[str, ...] = ()
    ce_include: tuple[str, ...] = ()
    ce_exclude: tuple[str, ...] = ()
    standards_include: tuple[str, ...] = ()
    standards_exclude: tuple[str, ...] = ()
    review_include: tuple[str, ...] = ()
    review_exclude: tuple[str, ...] = ()
    missing_include: tuple[str, ...] = ()
    missing_exclude: tuple[str, ...] = ()
    expected_scope_route: str | None = None
    expected_primary_route_family: str | None = None
    expected_primary_route_standard: str | None = None
    expected_product_type: str | None = None
    assert_primary_route: bool = False
    assert_product_type: bool = False


CALIBRATION_CASES: tuple[CalibrationCase, ...] = (
    CalibrationCase(
        name="non_radio_mains_appliance",
        description="230 V electric kettle, household use, no wireless connectivity",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED", "RED_CYBER"),
        ce_include=("LVD", "EMC"),
        ce_exclude=("RED",),
        standards_include=("EN 60335-2-15", "EN 60335-1", "EN 55014-1"),
        standards_exclude=("EN 62368-1",),
        missing_exclude=("cloud_dependency", "software_update_route", "smart_access_model"),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-15",
        expected_product_type="electric_kettle",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="smart_home_appliance_wifi_app",
        description="Smart washing machine with Wi-Fi, Bluetooth, cloud account, OTA firmware updates, 230 V mains",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        ce_include=("RED", "RED_CYBER"),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 60335-2-7", "EN 60335-1", "EN 301 489-1", "EN 300 328"),
        standards_exclude=("EN 62368-1",),
        review_include=("EN 18031-2",),
        missing_include=("radio_rf_detail", "data_storage_scope"),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-7",
        expected_product_type="washing_machine",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="battery_non_radio_device",
        description="Rechargeable handheld barcode scanner, battery powered, USB-C charging, no wireless connectivity",
        directives_include=("EMC", "BATTERY"),
        directives_exclude=("RED", "RED_CYBER"),
        ce_include=("LVD", "EMC"),
        ce_exclude=("RED",),
        standards_include=("EN 62368-1", "EN 55032", "EN 55035", "EN 62133-2"),
        missing_include=("battery_chemistry",),
        missing_exclude=("cloud_dependency", "software_update_route"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="industrial_handheld_scanner",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="bluetooth_only_accessory",
        description="Bluetooth-only accessory remote shutter button, coin-cell battery, no app account, no cloud",
        directives_include=("RED",),
        directives_exclude=("RED_CYBER", "LVD", "EMC"),
        ce_include=("RED",),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 300 328", "EN 301 489-1"),
        standards_exclude=("EN 62368-1",),
        missing_include=("radio_rf_detail", "battery_chemistry"),
        missing_exclude=("cloud_dependency", "smart_access_model"),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="radio_cloud_ota_product",
        description="Wi-Fi 6 mesh router with cloud account and OTA updates",
        directives_include=("RED", "RED_CYBER", "CRA", "GDPR"),
        directives_exclude=("LVD", "EMC"),
        ce_include=("RED", "RED_CYBER"),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 55032", "EN 301 893"),
        review_include=("EN 18031-2", "CRA review"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="mesh_wifi_system",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="wearable_sensor",
        description="Wearable heart-rate sensor chest strap with Bluetooth, skin contact, rechargeable battery",
        directives_include=("RED", "BATTERY", "GDPR"),
        directives_exclude=("LVD", "EMC", "RED_CYBER"),
        ce_include=("RED",),
        ce_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 62209-1528", "EN 50566"),
        review_include=("Biocompatibility / skin-contact review",),
        missing_include=("radio_rf_detail", "data_storage_scope", "body_contact_materials"),
        missing_exclude=("cloud_dependency", "smart_access_model"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict_wearable",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="heart_rate_monitor",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="household_60335_logic",
        description="Hair dryer, 230 V mains, consumer household use",
        directives_include=("LVD", "EMC"),
        directives_exclude=("RED",),
        standards_include=("EN 60335-2-23", "EN 60335-1"),
        standards_exclude=("EN 62368-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="household_appliance",
        expected_primary_route_standard="EN 60335-2-23",
        assert_primary_route=True,
    ),
    CalibrationCase(
        name="optical_led_product",
        description="Smart LED desk lamp with Wi-Fi app control, mains powered",
        directives_include=("RED", "RED_CYBER"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN IEC 62560", "EN 301 489-1"),
        review_include=("EN 62031",),
        expected_scope_route="appliance",
        expected_primary_route_family="lighting_device",
        expected_primary_route_standard="EN IEC 62560",
        expected_product_type="smart_desk_lamp",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="laser_product",
        description="Laser home projector, Wi-Fi, Bluetooth, mains powered, class 1 laser source",
        directives_include=("RED", "RED_CYBER"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN 62368-1", "EN 60825-1", "EN 62471"),
        expected_scope_route="av_ict",
        expected_primary_route_family="av_ict",
        expected_primary_route_standard="EN 62368-1",
        expected_product_type="home_projector",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="battery_handheld_tool",
        description="Cordless power drill, 18 V lithium-ion battery, consumer handheld tool",
        directives_include=("MD", "MACH_REG", "BATTERY"),
        directives_exclude=("RED", "LVD"),
        ce_include=("MD",),
        standards_include=("EN 62841-2-1", "EN 62841-1"),
        expected_scope_route="machinery",
        expected_primary_route_family="machinery_power_tool",
        expected_primary_route_standard="EN 62841-2-1",
        expected_product_type="cordless_power_drill",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="machine_like_powered_tool",
        description="Corded circular saw, 230 V, 1800 W, for professional wood cutting",
        directives_include=("MD", "MACH_REG"),
        directives_exclude=("RED",),
        review_include=("Power tool safety review",),
        expected_scope_route="machinery",
        expected_primary_route_family="machinery_power_tool",
        expected_primary_route_standard="Power tool safety review",
        expected_product_type="portable_power_saw",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ev_charging_station",
        description="Smart EV charging station wallbox, mode 3, AC charging, Type 2 connector, Wi-Fi, app control",
        directives_include=("RED", "RED_CYBER", "CRA"),
        directives_exclude=("LVD", "EMC"),
        standards_include=("EN IEC 61851-1", "EN IEC 61851-21-2"),
        review_include=("EN 62196-2",),
        expected_scope_route="appliance",
        expected_primary_route_family="ev_charging",
        expected_primary_route_standard="EN IEC 61851-1",
        expected_product_type="ev_charger_home",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ev_connector_cable",
        description="EV charging connector cable, Type 2 vehicle connector, tethered cable accessory only, no electronics",
        directives_include=("LVD",),
        directives_exclude=("RED",),
        review_include=("EN 62196-2",),
        standards_exclude=("EN IEC 61851-1",),
        expected_scope_route="appliance",
        expected_primary_route_family="ev_connector_accessory",
        expected_primary_route_standard="EN 62196-2",
        expected_product_type="ev_connector_accessory",
        assert_primary_route=True,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="simple_accessory",
        description="Passive USB-C to HDMI adapter cable, no radio, no battery",
        directives_exclude=("RED", "LVD"),
        standards_exclude=("EN 62368-1", "EN 60335-1"),
        missing_include=("external_psu",),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
    CalibrationCase(
        name="ambiguous_partial_facts",
        description="smart device for home use with app",
        directives_exclude=("RED", "LVD"),
        standards_exclude=("EN 62368-1", "EN 60335-1"),
        missing_include=("power_source", "cloud_dependency"),
        expected_scope_route="generic",
        expected_product_type=None,
        assert_product_type=True,
    ),
)


__all__ = ["CALIBRATION_CASES", "CalibrationCase"]
